"""Generate embedding vectors for processed text chunks.

This module handles the embedding stage of the Phase 1 pipeline:
- load chunk records produced by preprocessing.py
- initialize a local sentence-transformers embedding model once
- encode chunk text in batches on CPU
- convert embeddings to float32 for FAISS compatibility
- save enriched chunk records for downstream retrieval
"""

from __future__ import annotations

from pathlib import Path
from typing import Any
import argparse
import json
import logging

import numpy as np
from sentence_transformers import SentenceTransformer

try:
    from src.config import DATA_DIR
except ModuleNotFoundError:
    from config import DATA_DIR


LOGGER = logging.getLogger(__name__)
PROCESSED_DATA_DIR = DATA_DIR / "processed"
DEFAULT_INPUT_PATH = PROCESSED_DATA_DIR / "chunks.json"
DEFAULT_OUTPUT_PATH = PROCESSED_DATA_DIR / "embeddings.json"
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"


def load_chunks(input_path: Path | str = DEFAULT_INPUT_PATH) -> list[dict[str, Any]]:
    """Load processed chunk records from disk."""

    source = Path(input_path).expanduser().resolve()
    if not source.exists():
        raise FileNotFoundError(f"Chunks file does not exist: {source}")

    chunks = json.loads(source.read_text(encoding="utf-8"))
    if not isinstance(chunks, list):
        raise ValueError("Expected chunks JSON to contain a list of records.")

    required_keys = {"chunk_id", "text", "source", "page"}
    for index, chunk in enumerate(chunks, start=1):
        if not isinstance(chunk, dict):
            raise ValueError(f"Chunk at index {index} must be a JSON object.")
        missing_keys = required_keys - chunk.keys()
        if missing_keys:
            missing = ", ".join(sorted(missing_keys))
            raise ValueError(f"Chunk at index {index} is missing required keys: {missing}")

    return chunks


def load_model(model_name: str = EMBEDDING_MODEL_NAME) -> SentenceTransformer:
    """Load the embedding model once for reuse across all chunks."""

    LOGGER.info("Loading embedding model: %s", model_name)
    return SentenceTransformer(model_name, device="cpu")


def generate_embeddings(
    model: SentenceTransformer,
    texts: list[str],
) -> list[list[float]]:
    """Encode texts in one batch call and return float32 embedding vectors."""

    if not texts:
        return []

    embeddings = model.encode(
        texts,
        batch_size=32,
        convert_to_numpy=True,
        show_progress_bar=False,
        normalize_embeddings=False,
    )
    float32_embeddings = np.asarray(embeddings, dtype=np.float32)
    return float32_embeddings.tolist()


def attach_embeddings(
    chunks: list[dict[str, Any]],
    embeddings: list[list[float]],
) -> list[dict[str, Any]]:
    """Combine original chunk metadata with generated embedding vectors."""

    if len(chunks) != len(embeddings):
        raise ValueError(
            "Chunk count and embedding count must match: "
            f"{len(chunks)} chunks vs {len(embeddings)} embeddings."
        )

    embedded_chunks: list[dict[str, Any]] = []
    for chunk, embedding in zip(chunks, embeddings, strict=True):
        embedded_chunks.append(
            {
                "chunk_id": chunk["chunk_id"],
                "text": chunk["text"],
                "embedding": embedding,
                "source": chunk["source"],
                "page": chunk["page"],
            }
        )

    return embedded_chunks


def save_embeddings(
    records: list[dict[str, Any]],
    output_path: Path | str = DEFAULT_OUTPUT_PATH,
) -> Path:
    """Persist embedding records for downstream semantic retrieval."""

    destination = Path(output_path).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(records, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return destination


def build_argument_parser() -> argparse.ArgumentParser:
    """Create a CLI for local embedding runs."""

    parser = argparse.ArgumentParser(description="Generate embeddings for processed chunks.")
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT_PATH,
        help="Path to chunk JSON generated by preprocessing.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Path for saving embeddings JSON.",
    )
    return parser


def main() -> None:
    """Run the embedding pipeline and save embedding output."""

    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s | %(name)s | %(message)s",
    )

    parser = build_argument_parser()
    args = parser.parse_args()

    chunks = load_chunks(args.input)
    model = load_model()
    texts = [chunk["text"] for chunk in chunks]
    embeddings = generate_embeddings(model, texts)
    embedded_chunks = attach_embeddings(chunks, embeddings)
    output_path = save_embeddings(embedded_chunks, args.output)

    LOGGER.info("Loaded %s chunks.", len(chunks))
    LOGGER.info("Generated %s embedding vectors.", len(embeddings))
    LOGGER.info("Saved embeddings to %s", output_path)


if __name__ == "__main__":
    main()
